### ISSUE TITLE
ci: can we support generating and using local key pair for tests?

### ISSUE THREAD

**Issue by rchincha** [Duffney/setup-notation#2]

**Comment by dtzar** [comment]
It does do this automatically when you don't specify a plugin.
https://github.com/Duffney/setup-notation/blob/801eec7e43dc257b5cc3166468b4991ae3561ad1/dist/index.js#L52

Was there something else you were looking for?

**Comment by rchincha** [comment]
No, good to know. This looks ready to incorporate into zot's ci/cd.

**Comment by duffney** [comment]
Hi @rchincha, please let me know if there's anything else you need changed for the action. I'm happy to help.

**Comment by rchincha** [comment]
Thanks @Duffney, nothing right now, still testing this. Will definitely reach out.
